// @ts-check
/**
 * Reads .env from the project root and writes the resolved values into
 * projects/demo/src/app/environments/environment.ts.
 *
 * Usage: node scripts/set-env.js
 * Automatically invoked via the "prestart" and "prebuild:demo" npm scripts.
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envFile = path.join(rootDir, '.env');
const targetFile = path.join(rootDir, 'projects/demo/src/app/environments/environment.ts');

/**
 * Parses a .env file and returns a key/value map.
 * Lines starting with '#' and empty lines are ignored.
 *
 * @param {string} filePath - Absolute path to the .env file.
 * @returns {Record<string, string>}
 */
function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    console.warn(`[set-env] No .env file found at "${filePath}". Placeholder values will be used.`);
    return {};
  }

  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  /** @type {Record<string, string>} */
  const result = {};

  for (const line of lines) {
    const trimmed = line.trim();
    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    result[key] = value;
  }

  return result;
}

const env = parseEnv(envFile);

// Read Cognito values from .env, falling back to safe placeholder strings.
const userPoolId = env['COGNITO_USER_POOL_ID'] ?? 'us-east-1_XXXXXXXXX';
const clientId   = env['COGNITO_CLIENT_ID']    ?? 'YOUR_CLIENT_ID';
const domain     = env['COGNITO_DOMAIN']       ?? 'your-domain.auth.us-east-1.amazoncognito.com';
const redirectUri = env['COGNITO_REDIRECT_URI'] ?? 'http://localhost:4200/callback';

// Generate the environment.ts file content.
const content = `import { CognitoAuthConfig } from 'ngx-cognito-auth';

// This file is auto-generated by scripts/set-env.js.
// Values are sourced from the .env file in the project root.
// Do NOT edit this file manually — update .env instead.

export const environment = {
  production: false,
  cognito: {
    userPoolId: '${userPoolId}',
    clientId: '${clientId}',
    domain: '${domain}',
    redirectUri: '${redirectUri}',
    scopes: ['openid', 'email', 'profile'],
    // Redirect to the private dashboard after a successful login.
    postLoginRoute: '/dashboard',
    // Redirect to the public home page after logout.
    postLogoutRoute: '/',
    storageKeyPrefix: 'demo_auth',
  } satisfies CognitoAuthConfig,
};
`;

fs.writeFileSync(targetFile, content, 'utf8');
console.log('[set-env] environment.ts generated successfully.');
